version: "3.8"

services:
  # back
  back-end:
    build:
      dockerfile: Dockerfile
      context: ./back-end
      target: development
    restart: always
    volumes:
      - ./back-end:/camagru/back-end/
      - back-end-node-modules:/camagru/back-end/node_modules/
      - back-end-upload:/camagru/upload/
    command: npm run serve
    environment:
      DB_CONN: ${DB_CONN}
      DB_NAME: ${DB_NAME}
      DB_USER_COLL_NAME: ${DB_USER_COLL_NAME}
      DB_FILE_COLL_NAME: ${DB_FILE_COLL_NAME}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    ports:
      - "3000:3000"
    networks:
      - camagru_net

  # front
  front-end:
    build:
      dockerfile: Dockerfile
      context: ./front-end
      target: development
    retart: always
    volumes:
      - ./front-end:/usr/share/nginx/html
    command: nginx -g "daemon off;"
    deponds_on:
      - back_end
    ports:
      - "80:80"
    networks:
      - camagru_net

  volumes:
    back-end-upload:

  networks:
    camagru_net:
      driver: bridge

